# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  auctionservice:
    image: ahmedhafez33/auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__Default=Server=postgres:5432; User Id=postgres; Password=postgres; Database=auctions
      - IdentityServiceUrl=http://identityservice
    ports:
      - '7001:8080'
    depends_on:
      - postgres
      - rabbitmq

  searchservice:
    image: ahmedhafez33/searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__Default=mongodb://root:mongo@mongo
      - AuctionServiceUrl=http://auctionservice
    ports:
      - '7002:8080'
    depends_on:
      - postgres
      - rabbitmq
