# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  auctionservice:
    image: auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7001:7001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
